### ISSUE TITLE
Status codes in the response

### ISSUE THREAD

**Issue by AlexBSiteEye** [time-lapse-api/docs#4]
I've noticed some of the responses on the API have a "status" field.

Does anyone have a list of status codes anywhere to indicate what this means?

**Comment by peteredhead** [comment]
Looking at the current API code, the status response appears to mimic shell exit codes (i.e. zero is a success and anything non-zero is an error) but I cannot find any list of what the codes actually mean.

This feels to me like it is already covered in the HTTP status response. In the event of an error, a reason could be returned in the response body. Are there any situations where an error would not map to a corresponding HTTP status code?

**Comment by AlexBSiteEye** [comment]
I agree that HTTP status codes would be more useful here. I can't think of any scenarios where custom errors would be required. I propose removing the 'status' field from all responses.

Pete - if that's ok with you guys can you close this issue? Thanks.

**Comment by peteredhead** [comment]
Removed the status fields and created a new pull request.
Not sure what the etiquette is for accepting your own pull requests :)
